name: push-to-blog

on:
  push:
    branches:
      - main  # 触发条件，当 main 分支有 push 事件时触发

jobs:
  push-to-blog:
    runs-on: ubuntu-latest 

    steps:
      - name: Setup Git
        uses: actions/checkout@v2

      - name: Clone Blog Repo
        uses: actions/checkout@v2
        with:
         repository: blockhaity/blockhaity.github.io
         ref: main
         path: blockhaity.github.io
         token: $ {{ secrets.GITHUB_TOKEN }}

      - name: Clone Blog Repo
        uses: actions/checkout@v2
        with:
         repository: blockhaity/studynotes
         ref: main
         path: studynotes
         token: $ {{ secrets.GITHUB_TOKEN }}

      - name: Copy Files
        run:  |
          mkdir ./blockhaity.github.io/source/studynotes
          cp -rf ./studynotes/* ./blockhaity.github.io/source/studynotes
          rm -rf ./blockhaity.github.io/source/studynotes/.git
          rm -rf ./blockhaity.github.io/source/studynotes/.github
          rm -rf ./blockhaity.github.io/source/studynotes/img
          cp -rf ./studynotes/img/* ./blockhaity.github.io/source/img
      
      - name: Push to Blog
        run: |
          cd ./blockhaity.github.io
          git config --global user.email "1216692740@qq.com"
          git config --global user.name "BlockHaity" 
          git add .
          git commit -m "update blog"
          git push origin main --force